### ISSUE TITLE
catkin_makeでエラー

### ISSUE THREAD

**Issue by hasidume** [tork-a/jog_control#12]
jog_controlのソースをGitHubからダウンロードして、catkin_makeしたところ、
以下のエラーが発生しました。何が原因でしょうか？

CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by
  "moveit_visual_tools" with any of the following names:

    moveit_visual_toolsConfig.cmake
    moveit_visual_tools-config.cmake

  Add the installation prefix of "moveit_visual_tools" to CMAKE_PREFIX_PATH
  or set "moveit_visual_tools_DIR" to a directory containing one of the above
  files.  If "moveit_visual_tools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  jog_control/jog_controller/CMakeLists.txt:6 (find_package)

-- Could not find the required component 'moveit_visual_tools'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "moveit_visual_tools" with any of the following names:

    moveit_visual_toolsConfig.cmake
    moveit_visual_tools-config.cmake

  Add the installation prefix of "moveit_visual_tools" to CMAKE_PREFIX_PATH
  or set "moveit_visual_tools_DIR" to a directory containing one of the above
  files.  If "moveit_visual_tools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  jog_control/jog_controller/CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/rosusr/ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/rosusr/ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by 7675t** [comment]
jog_controllerがmoveit_visual_toolsパッケージに依存していますが，パッケージがシステムにインストールされていないためにビルドできないようです．

```
$ cd ~ws
$ rosdep install -r --from-path src --ignore-src
```

とすると，ビルド時に依存するパッケージを自動でaptで取得することができます．
その後，もう一度ビルドしてみてください．

**Comment by hasidume** [comment]
ご教授頂きました方法で、catkin_makeは通りました。
有難う御座いました。
