### ISSUE TITLE
Not installing on ROS Kinetic

### ISSUE THREAD

**Issue by pulkit123tak** [tork-a/jog_control#17]
Hi 

I am trying to install this package from source for my project. However while following the installation instructions given, it always shows an error like this, on entering wstool update command: 

>  ERROR in config: Command requires a target workspace.
Kindly refer to this issue fast.

**Comment by Moirai** [comment]
Hi,
Please try this one.
~~~
wstool update -t src
~~~

**Comment by 7675t** [comment]
Thanks for reporting. Please try as follows:

```
$ source /opt/ros/kinetic/setup.bash
$ mkdir -p ws/src
$ cd ws
$ wstool init src
$ wstool set -t src jog_control --git http://github.com/tork-a/jog_control
$ wstool update -t src
$ rosdep install -r --from-path src
$ catkin build
$ source devel/setup.bash
```
I will fix the document later.
