### ISSUE TITLE
Error when executing roslaunch

### ISSUE THREAD

**Issue by hasidume** [tork-a/jog_control#18]
The following error occurred when executing roslaunch.

auto-starting new master
process[master]: started with pid [27995]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 05db9056-8b13-11e8-a5d8-0800272a43d6
process[rosout-1]: started with pid [28008]
started core service [/rosout]
process[jog_joint_node-2]: started with pid [28025]
process[jog_frame_node-3]: started with pid [28028]
[ERROR] [1531977447.322938718]: move_group/controller_list is not specified.
[ERROR] [1531977447.324767707]: get_controller_list faild. Aborted.
[ERROR] [1531977447.346138192]: move_group/controller_list is not specified.
[ERROR] [1531977447.346320660]: get_controller_list faild. Aborted.
[jog_joint_node-2] process has finished cleanly
log file: /home/rosusr/.ros/log/05db9056-8b13-11e8-a5d8-0800272a43d6/jog_joint_node-2*.log
[jog_frame_node-3] process has finished cleanly
log file: /home/rosusr/.ros/log/05db9056-8b13-11e8-a5d8-0800272a43d6/jog_frame_node-3*.log

**Comment by 7675t** [comment]
It looks you launched only  the launch file for jog_controller. The jog_control nodes need to read some MoveIt!'s parameters to initialize, so it should be launched after MoveIt! launched. The examples in README.md shows the jog_controller launch file is started after the robot simulator(MoveIt!).

We may need to consider to use dynamic_reconfigure to avoid this limitation. Thanks.

**Comment by hasidume** [comment]
I described the launch file and yaml file for my robot but the problem was solved.
