### ISSUE TITLE
How to create a robot launch file

### ISSUE THREAD

**Issue by hasidume** [tork-a/jog_control#19]
~ / ws / src / jog_control / jog_controller / launch
Is there a manual on how to create a robot launch file stored in?

**Comment by 7675t** [comment]
I opened pull request #21 for this issue. Please check if this file can answer your question.

- https://github.com/tork-a/jog_control/blob/42b62f9dec0473ad16e6cd3c3f57ab3ed5353c4d/jog_controller/README.md

And I append some comments on tra1_jog.yaml for setting.

- https://github.com/tork-a/jog_control/blob/42b62f9dec0473ad16e6cd3c3f57ab3ed5353c4d/jog_controller/config/tra1_jog.yaml

**Comment by hasidume** [comment]
The problem was solved with reference to the manual.
