### ISSUE TITLE
motoman_sia20d.launch error

### ISSUE THREAD

**Issue by LazyEngineerToBe** [tork-a/jog_control#34]
When launching the motoman_sia20d, I get this error.
`
RLException: error loading <rosparam> tag: 
	file does not exist [/home/alex/Code/catkin_ws/src/jog_control/jog_controller/config/motoman_sia20d_jog.yaml]
XML is <rosparam command="load" file="$(find jog_controller)/config/motoman_sia20d_jog.yaml"/>
The traceback for the exception was written to the log file
`
The launch file is looking for the config file in the wrong package. It should look in the jog_launch package. I fixed it locally and it worked fine.

This is an awesome package btw..

**Comment by 7675t** [comment]
Could you make a PR of your fix? Thanks!

**Comment by 7675t** [comment]
#35 fixed this. Thank you!
