### ISSUE TITLE
[Question] dynamic reconfigure

### ISSUE THREAD

**Issue by LazyEngineerToBe** [tork-a/jog_control#40]
Hi,

I'm trying to change the base_link at run time, just like in the rviz jog_frame_panel, I'm thinking of using a ROS service. I'm a bit confused about where I should implement it. Should dynamic reconfigure be implemented in the jog_frame_node of in the joy_to_jog_frame node? @7675t

**Comment by 7675t** [comment]
Do you mean you want to set the reference frame (origin) of the target link at run time? I'm using JogFrame message for such purpose, so why don't you use it?

https://github.com/tork-a/jog_control/blob/master/jog_msgs/msg/JogFrame.msg

In this message header.frame_id must be set as a reference frame (ordinary base_frame). If your intent is different, please let me know.

**Comment by LazyEngineerToBe** [comment]
That's what I was looking for, thank you!
