### ISSUE TITLE
Using a different inverse kinematics solver

### ISSUE THREAD

**Issue by m-talha** [tork-a/jog_control#41]
I would like to use a different IK algorithm from the MoveIt library than the one currently in use as it doesn't work very well for my current 6-DOF arm. Can you guide me on how to go about doing this? Thanks

**Comment by 7675t** [comment]
All nodes in jog_control just use `compute_ik` service of MoveIt! . So you can change your MoveIt! settings for IK and so in jog_control.

The IK setting of MoveIt! is described [around here](http://docs.ros.org/melodic/api/moveit_tutorials/html/doc/kinematics_configuration/kinematics_configuration_tutorial.html).

**Comment by 7675t** [comment]
You are welcome.
